### ISSUE TITLE
When PEM file is used, it gets deleted after command is run

### ISSUE THREAD

**Issue by plermant** [akshayranganath/akamai-open-fossl#1]
The location of the PEM file is deleted. the PEM file should be left alone after the command runs

**Comment by akshayranganath** [comment]
I've disable the deletion of the PEM file. By default, the PEM file will be named as _cert.txt_.

**Comment by akshayranganath** [comment]
The current fix is a stop-gap. I'll add the ability to not delete the cert file when it was already provided.

**Comment by akshayranganath** [comment]
The issue is now fixed.
